spring.application.name=blog_app
spring.datasource.url=jdbc:postgresql://localhost:5432/blog_app
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=your_very_secret_key_here
